# Generated by Django 3.1 on 2020-10-30 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20201030_2138'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BlogpostGrade2',
            new_name='Grade2blogpost',
        ),
        migrations.RenameModel(
            old_name='BlogpostGrade3',
            new_name='Grade3blogpost',
        ),
        migrations.RenameModel(
            old_name='BlogpostGrade4',
            new_name='Grade4blogpost',
        ),
    ]
