# Generated by Django 3.1 on 2020-11-03 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20201030_2144'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade2blogpost',
            name='file',
            field=models.FileField(default='blog/downloads/empty.pdf', upload_to='blog/downloads/'),
        ),
        migrations.AddField(
            model_name='grade3blogpost',
            name='file',
            field=models.FileField(default='blog/downloads/empty.pdf', upload_to='blog/downloads/'),
        ),
        migrations.AddField(
            model_name='grade4blogpost',
            name='file',
            field=models.FileField(default='blog/downloads/empty.pdf', upload_to='blog/downloads/'),
        ),
    ]
