# Generated by Django 3.1 on 2020-11-03 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20201103_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade2blogpost',
            name='file',
            field=models.FileField(default='blog/lessonplans/empty.pdf', upload_to='blog/lessonplans/'),
        ),
        migrations.AlterField(
            model_name='grade3blogpost',
            name='file',
            field=models.FileField(default='blog/lessonplans/empty.pdf', upload_to='blog/lessonplans/'),
        ),
        migrations.AlterField(
            model_name='grade4blogpost',
            name='file',
            field=models.FileField(default='blog/lessonplans/empty.pdf', upload_to='blog/lessonplans/'),
        ),
    ]
