# Generated by Django 3.1 on 2020-11-17 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20201103_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade2blogpost',
            name='grade',
            field=models.CharField(default='Grade 2', max_length=10),
        ),
        migrations.AddField(
            model_name='grade3blogpost',
            name='grade',
            field=models.CharField(default='Grade 3', max_length=10),
        ),
        migrations.AddField(
            model_name='grade4blogpost',
            name='grade',
            field=models.CharField(default='Grade 4', max_length=10),
        ),
    ]
