# Generated by Django 3.1 on 2020-12-15 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20201215_1406'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade2blogpost',
            name='image',
            field=models.ImageField(default='blog/images/soon.png', upload_to='blog/images'),
        ),
        migrations.AddField(
            model_name='grade2blogpost',
            name='imagecredits',
            field=models.TextField(default='Image from pixabay.com', max_length=10),
        ),
        migrations.AddField(
            model_name='grade3blogpost',
            name='image',
            field=models.ImageField(default='blog/images/soon.png', upload_to='blog/images'),
        ),
        migrations.AddField(
            model_name='grade3blogpost',
            name='imagecredits',
            field=models.TextField(default='Image from pixabay.com', max_length=10),
        ),
        migrations.AddField(
            model_name='grade4blogpost',
            name='image',
            field=models.ImageField(default='blog/images/soon.png', upload_to='blog/images'),
        ),
        migrations.AddField(
            model_name='grade4blogpost',
            name='imagecredits',
            field=models.TextField(default='Image from pixabay.com', max_length=10),
        ),
        migrations.AlterField(
            model_name='grade2blogpost',
            name='intro',
            field=models.TextField(default='intro', max_length=400),
        ),
        migrations.AlterField(
            model_name='grade3blogpost',
            name='intro',
            field=models.TextField(default='intro', max_length=400),
        ),
    ]
