# Generated by Django 3.1 on 2020-12-15 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20201215_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade2blogpost',
            name='imagecredits',
            field=models.TextField(default='Image from pixabay.com', max_length=200),
        ),
        migrations.AlterField(
            model_name='grade3blogpost',
            name='imagecredits',
            field=models.TextField(default='Image from pixabay.com', max_length=200),
        ),
        migrations.AlterField(
            model_name='grade4blogpost',
            name='imagecredits',
            field=models.TextField(default='Image from pixabay.com', max_length=200),
        ),
    ]
