# Generated by Django 3.1 on 2020-12-15 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20201215_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade2blogpost',
            name='image',
            field=models.ImageField(default='blog/images/soon.png', upload_to='blog/images/'),
        ),
        migrations.AlterField(
            model_name='grade3blogpost',
            name='image',
            field=models.ImageField(default='blog/images/soon.png', upload_to='blog/images/'),
        ),
        migrations.AlterField(
            model_name='grade4blogpost',
            name='image',
            field=models.ImageField(default='blog/images/soon.png', upload_to='blog/images/'),
        ),
    ]
