# Generated by Django 3.1.4 on 2021-01-03 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20201215_2354'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grade2blogpost',
            name='imagecredits',
        ),
        migrations.RemoveField(
            model_name='grade3blogpost',
            name='imagecredits',
        ),
        migrations.RemoveField(
            model_name='grade4blogpost',
            name='imagecredits',
        ),
        migrations.AddField(
            model_name='grade2blogpost',
            name='credits',
            field=models.TextField(blank='True'),
        ),
        migrations.AddField(
            model_name='grade3blogpost',
            name='credits',
            field=models.TextField(blank='True'),
        ),
        migrations.AddField(
            model_name='grade4blogpost',
            name='credits',
            field=models.TextField(blank='True'),
        ),
    ]
