# Generated by Django 3.1.4 on 2021-01-03 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20210103_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade2blogpost',
            name='file',
            field=models.FileField(blank='True', upload_to='blog/downloads/'),
        ),
        migrations.AlterField(
            model_name='grade3blogpost',
            name='file',
            field=models.FileField(blank='True', upload_to='blog/downloads/'),
        ),
        migrations.AlterField(
            model_name='grade4blogpost',
            name='file',
            field=models.FileField(blank='True', upload_to='blog/downloads/'),
        ),
    ]
